<?php
include_once( "../../global.php" );
$db = new plate( $mydbhost, $mydbuser, $mydbpw, $mydbname, ALL_PS, $mydbcharset );
$db2 = new plate( $mydbhost, $mydbuser, $mydbpw, $mydbname, ALL_PS, $mydbcharset );
$query = "select * from system_marquee where type=0 ";
$result_all = mysql_query( $query );
$total = mysql_num_rows( $result_all );
pageft( $total, 10 );
if ( $firstcount < 0 )
{
		$firstcount = 0;
}
$result = mysql_query( "{$query} order by datetime desc limit  {$firstcount}, {$displaypg}" );
echo "<html oncontextmenu=\"return false\" xmlns=\"http://www.w3.org/1999/xhtml\"><head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n";
echo "<s";
echo "tyle type=\"text/css\">\r\n<!--\r\nbody {\r\n\tmargin-left: 0px;\r\n\tmargin-top: 0px;\r\n\tmargin-right: 0px;\r\n\tmargin-bottom: 0px;\r\n}\r\n-->\r\n</style>\r\n</head>\r\n<body oncontextmenu=\"return false\" onselect=\"document.selection.empty()\" oncopy=\"document.selection.empty()\" onmouseover=\"self.status='šgÓ­¹âÅR';return true\">\r\n<link href=\"../images/Index.css\" rel=\"stylesheet\" type=\"text/css\">\r\n ";
echo "<s";
echo "cript language=\"JavaScript\">\r\nfunction send_request(url){//³õÊ¼»¯£¬Ö¸¶¨ÌŽÀíº¯Êý£¬°lËÍÕˆÇóµÄº¯Êý\r\n    http_request=false;\r\n    //é_Ê¼³õÊ¼»¯XMLHttpRequestŒ¦Ïó\r\n    if(window.XMLHttpRequest){//MozillažgÓ[Æ÷\r\n     http_request=new XMLHttpRequest();\r\n     if(http_request.overrideMimeType){//ÔOÖÃMIMEî„e\r\n       http_request.overrideMimeType(\"text/xml\");\r\n     }\r\n    }\r\n    else if(window.ActiveXObject)";
echo "{//IEžgÓ[Æ÷\r\n     try{\r\n      http_request=new ActiveXObject(\"Msxml2.XMLHttp\");\r\n     }catch(e){\r\n      try{\r\n      http_request=new ActiveXobject(\"Microsoft.XMLHttp\");\r\n      }catch(e){}\r\n     }\r\n    }\r\n    if(!http_request){//®³££¬„“½¨Œ¦ÏóŒÀýÊ§”¡\r\n     window.alert(\"„“½¨XMLHttpŒ¦ÏóÊ§”¡£¡\");\r\n     return false;\r\n    }\r\n    http_request.onreadystatechange=processrequest;\r\n    //´_¶¨°lËÍÕˆÇó·½Ê½£";
echo "¬URL£¬¼°ÊÇ·ñÍ¬²½ˆÌÐÐÏÂ¶Î´úÂë\r\n    http_request.open(\"GET\",url,true);\r\n    http_request.send(null);\r\n  }\r\n  //ÌŽÀí·µ»ØÐÅÏ¢µÄº¯Êý\r\n  function processrequest(){\r\n   if(http_request.readyState==4){//ÅÐ”àŒ¦Ïó î‘B\r\n     if(http_request.status==200){//ÐÅÏ¢ÒÑ³É¹¦·µ»Ø£¬é_Ê¼ÌŽÀíÐÅÏ¢\r\n\t \r\n      document.getElementById(reobj).innerHTML=http_request.responseText;\r\n\t  \r\n     }\r\n     else{//í“Ãæ²»Õý³£\r\n      ale";
echo "rt(\"ÄúËùÕˆÇóµÄí“Ãæ²»Õý³££¡\");\r\n     }\r\n   }\r\n  }\r\n  function dopage(obj,url){\r\n  // document.getElementById(obj).innerHTML=\"ÕýÔÚ×xÈ¡Êý“þ...\";\r\n   send_request(url);\r\n   reobj=obj;\r\n   } \r\n   \r\n function C_Key(){\r\n\tvar key=document.all.key.value;\r\n\tdopage('result','?spul=DmgAXFE9UTwCCghrAiEIaQ!888!888&key='+key+'&page=1');\r\n}\r\n\r\n</script>\r\n\r\n ";
echo "<s";
echo "tyle type=\"text/css\">\r\n<!--\r\n.STYLE1 {color: #CCCCCC}\r\n-->\r\n </style>\r\n <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\r\n  <tbody>\r\n    <tr>\r\n      <td background=\"../images/tab_05.gif\" height=\"30\"><table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\r\n        <tbody>\r\n          <tr>\r\n            <td height=\"30\" width=\"12\"><img src=\"../images/tab_03.gif\" height=\"30\" width=\"12\"></td>\r";
echo "\n            <td><table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\r\n              <tbody>\r\n                <tr>\r\n                  <td valign=\"middle\" width=\"87%\"><table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\r\n                    <tbody>\r\n                      <tr>\r\n                        <td width=\"1%\"><div align=\"center\"><img src=\"../images/tb.gif\" height=\"16\" width=\"16\"></d";
echo "iv></td>\r\n                        <td class=\"F_bold\" width=\"32%\">Õ¾ÄÚÐÅÏ¢</td>\r\n                        <td class=\"F_bold\" width=\"67%\"></td>\r\n                      </tr>\r\n                    </tbody>\r\n                  </table></td>\r\n                  </tr>\r\n              </tbody>\r\n            </table></td>\r\n            <td width=\"16\"><img src=\"../images/tab_07.gif\" height=\"30\" width=\"16\"></td>\r\n          </tr>\r\n ";
echo "       </tbody>\r\n      </table></td>\r\n    </tr>\r\n    <tr>\r\n      <td><table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\r\n        <tbody>\r\n          <tr>\r\n            <td background=\"../images/tab_12.gif\" width=\"8\">&nbsp;</td>\r\n            <td align=\"center\" height=\"50\"><!-- é_Ê¼  --><div id=\"result\">              <table class=\"t_list\" border=\"0\" cellpadding=\"0\" cellspacing=\"1\" width=\"100%\">\r\n       ";
echo "         <tbody><tr>\r\n                  <td class=\"t_list_caption\">ÙN³ö•rég</td>\r\n                  <td class=\"t_list_caption\">ÏûÏ¢Ô”Çé</td>\r\n                </tr>\r\n                <tr style=\"\" class=\"t_list_tr_0\" onMouseOver=\"this.style.backgroundColor='#FFFFA2'\" onMouseOut=\"this.style.backgroundColor=''\">\r\n                  <td class=\"F_bold\">¹«Ë¾ÒŽ„t</td>\r\n                  <td align=\"left\"><table style=\"T";
echo "ABLE-LAYOUT: fixed\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"800\">\r\n                      <tbody><tr>\r\n                        <td style=\"word-wrap:break-word;white-Space:AD_Info;\" class=\"F_bold\"><ad_info><br>\r\n                              <br>\r\n                          ®”Äú¼ÓÈë±¾¹«Ë¾³Éžé¹ÜÀíŒÓ•r£¬Äú±ØíšÇå³þÁË½â¼°×ñÄ±¾¹«Ë¾µÄËùÓÐ—lÀý¡£ÄúÔÚ±¾¹«Ë¾¾WÕ¾é_³öµÄµÚÒ»‚€ÏÂ¾€•r£¬¾Í´ú±íÄúÒÑÍ¬Òâ¼°½ÓÊÜËùÓÐ";
echo "±¾¹«Ë¾µÄ<a href=\"javascript:void(0)\" onClick=\"document.getElementById('Rele_Div').style.display='block';\" class=\"font_R\">¡¶ÒŽ„t¼°—lÀý¡·</a>¡£<br>\r\n                          <br>\r\n                          <div id=\"Rele_Div\" style=\"display: none;position:absolute; background-color: #ffffa2\"> 1¡¢Ê¹ÓÃ±¾¹«Ë¾¾WÕ¾µÄ¸÷¹É–|ºÍ´úÀíÉÌ£¬ÕˆÁôÒâéwÏÂËùÔÚµÄ‡ø¼Ò»ò¾Ó×¡µØµÄÏàêP·¨ÂÉÒŽ¶¨£¬ÈçÓÐÒÉ†–‘ª¾ÍÏàêP†–î}£¬Œ¤Çó®”µØ·¨ÂÉ";
echo "ÒâÒŠ¡£<br>\r\n                  <br>\r\n                            2¡¢Èô°lÉúÔâñ”¿ÍÈëÇÖÆÆ‰ÄÐÐžé»ò²»¿É¿¹¾ÜÖ®žÄº¦Œ§ÖÂ¾WÕ¾¹ÊÕÏ»òÙYÁÏ“p‰Ä¡¢ÙYÁÏGÊ§µÈÇé›r£¬ÎÒ‚ƒŒ¢ÒÔ±¾¹«Ë¾Ö®áá‚äÙYÁÏžé×îááÌŽÀíÒÀ“þ¡£<br>\r\n                            <br>\r\n                            3¡¢é_ª„½yÓ‹µÈÙYÁÏÖ»¹©…¢¿¼£¬²¢·ÇÊÇŒ¦¿Í‘ô²Ù×÷µÄÖ¸Òý£¬±¾¹«Ë¾Ò²²»½ÓÊÜêPì¶½yÓ‹Êý“þ®aÉúåeÕ`¶øÒýÆðµÄÏàêPÍ¶ÔV¡£<br>\r\n                            <br>\r\n        ";
echo "                    4¡¢‡øëH¾WÂ·µÄÁ¬½ÓËÙ¶ÈK·Ç±¾¹«Ë¾ËùÄÜ¿ØÖÆ£¬±¾¹«Ë¾Ò²²»½ÓÊÜêPì¶¾WÂ·ÒýÆðµÄÏàêPÍ¶ÔV¡£<br>\r\n                            <br>\r\n                            5¡¢ÓÉì¶‚S½y·þ„ÕÉæ¼°¸ß¶ËµÄ¼¼ÐgÒªÇó¼°Íâ‡úËù²»ÄÜ¿ØÖÆµÄÒòËØÏÞÖÆ£¬Òò´Ë‚S½yµÄÎÈ¶¨ÐÔ£¬Á¬ÀmÐÔ•þÓÐ•rÊÜµ½Ó°í‘£¬±¾¹«Ë¾Ò²²»³Ðµ£ÓÉ´Ë¶ø®aÉúµÄ“pÊ§¡£<br>\r\n                            <br>\r\n                            6¡¢¸÷¹É–|ºÍ´úÀíÉÌ±ØíšÁôÒâÏÂ¾€µÄÐÅÓÃî";
echo "~¶È£¬ÔÚÄ³·NÌØÊâÇé›rÏÂ£¬ÏÂÏßÖ®ÐÅÓÃî~¿ÉÄÜ•þ³ö¬FÍ¸Ö§¡£<br>\r\n                            <br>\r\n                            7¡¢±¾¹«Ë¾“íÓÐÒ»ÇÐÅÐ›Q¼°Ô]ÏûÈÎºÎÉæÏÓÒÔ·ÇÕý³£·½Ê½ÏÂÔ]Ô]µ¥Ö®™àÀû£¬ÔÚßMÐÐÕ{²éÆÚégŒ¢Í£Ö¹°l·ÅÅcÆäÓÐêPÖ®ÈÎºÎ²Ê½ð¡£<br>\r\n                            <br>\r\n                            8¡¢¿Í‘ôÓÐØŸÈÎ´_±£×Ô¼ºµÄŽ¤‘ô¼°ÃÜÂëµÄ°²È«£¬Èç¹û¿Í‘ô‘ÑÒÉ×Ô¼ºµÄÙYÁÏ±»±IÓÃ£¬‘ªÁ¢¼´Í¨Öª±¾¹«Ë¾£¬Kíš¸ü¸ÄÆä‚€ÈËÔ”¼šÙYÁ";
echo "Ï¡£ËùÓÐ±»±IÓÃŽ¤Ì–Ö®“pÊ§Œ¢ÓÉ¿Í‘ô×ÔÐÐØ“ØŸ¡£<br>\r\n                            <br>\r\n                            \r\n9¡¢±¾¹«Ë¾²»½ÓÊÜÈÎºÎÈËÒÔÈÎºÎÀíÓÉÒªÇóÔ]äN•þ†TÏÂÔ]µÄÔ]µ¥£¬¶ø²»Õ“Ô“Ô]µ¥ÊÇ·ñÒÑÓÐé_ª„½Y¹û£¬³ý·Ç¸ÃÔ]µ¥ÊÇÓÉÓÚ‚S½y³öÏÖ´íÎó»òÈËÎª²Ù×÷Ôì³É³ö¬FÅâÂÊ´íÎóµÄÔ]\r\nµ¥£¬¶ø¡°ÅâÂÊ´íÎó¡±ƒH¶¨Òåì¶£º(1)ŸoÕ“³ö¬FÈÎºÎé_ª„½Y¹û£¬•þ†TßMÐÐµ¥í—Ä¿ÏÂ×¢µÄÔ]µ¥½á¹û¶¼Ÿo·¨«@Àû£¬»ò \r\n(2)ŸoÕ“³ö¬FÈÎºÎé_ª„½Y¹û£¬•þ†TÔÚÍ¬Ò»•régÈç¹ûßMÐÐ¶";
echo "àí—Ä¿ÏÂÔ]µÄ¿‚½á¹û¶¼ÄÜ«@Àû¡£<br>\r\n                            <br>\r\n                            10£¬±¾ÒŽ„t¼°—lÀýµÄ½âÊÍ™à¼°ÐÞ¸Ä™àšw±¾¹«Ë¾ËùÓÐ¡£<br>\r\n                            <br>\r\n                            <br>\r\n¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡\r\n¡°¸ß²ã¹ÜÀí                \" ¾´†¢<br>\r\n                          </div>\r\n                          ";
echo "<br>\r\n                        </ad_info></td>\r\n                      </tr>\r\n                  </tbody></table></td>\r\n                </tr>\r\n                \r\n                ";
while ( $row = mysql_fetch_array( $result ) )
{
		echo "                <tr style=\"\" class=\"t_list_tr_0\" onMouseOver=\"this.style.backgroundColor='#FFFFA2'\" onMouseOut=\"this.style.backgroundColor=''\">\r\n                  <td>";
		echo date( "Y-m-d H:i:s", $row['datetime'] );
		echo "</td>\r\n                  <td align=\"left\">\r\n                  <table style=\"TABLE-LAYOUT: fixed\" border=\"0\" cellpadding=\"2\" cellspacing=\"2\" width=\"800\">\r\n                      <tbody>\r\n                      <tr>\r\n                        <td style=\"word-wrap:break-word;white-Space:AD_Info;\" align=\"left\">\r\n                        <ad_info>\r\n                            ";
		echo $row['content'];
		echo "                     \r\n                         </ad_info>\r\n                        </td>\r\n                      </tr>\r\n                  </tbody>\r\n                  </table>\r\n                  </td>\r\n                </tr>\r\n                \r\n                   ";
}
echo "  \r\n                  </tbody>\r\n                  </table>\r\n              </div> <!-- ½YÊø  --></td>\r\n            <td background=\"../images/tab_15.gif\" width=\"8\">&nbsp;</td>\r\n          </tr>\r\n        </tbody>\r\n      </table></td>\r\n    </tr>\r\n    <tr>\r\n      <td background=\"../images/tab_19.gif\" height=\"35\"><table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\r\n        <tbody>\r\n          <tr>\r\n           ";
echo " <td height=\"35\" width=\"12\"><img src=\"../images/tab_18.gif\" height=\"35\" width=\"12\"></td>\r\n            <td valign=\"top\"><table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" height=\"30\" width=\"100%\">\r\n              <tbody>\r\n                <tr>\r\n                  <td align=\"center\">&nbsp;";
echo $pagenav;
echo "</td>\r\n                </tr>\r\n              </tbody>\r\n            </table></td>\r\n            <td width=\"16\"><img src=\"../images/tab_20.gif\" height=\"35\" width=\"16\"></td>\r\n          </tr>\r\n        </tbody>\r\n      </table></td>\r\n    </tr>\r\n  </tbody>\r\n</table>\r\n\r\n</body></html>";
?>
