<?php
include_once( "../../global.php" );
$get_user_limit = $_GET['get_user_limit'];
$t1 = $_GET['t1'];
$t2 = $_GET['t2'];
$db = new action( $mydbhost, $mydbuser, $mydbpw, $mydbname, ALL_PS, $mydbcharset );
$user_limit = $db->get_user_limit_char( $get_user_limit, $t1, $t2 );
if ( $user_limit )
{
		$user_limit = " and ".$user_limit;
}
$query = $db->select( "users", "count(*) as c", "user_power=6 {$user_limit}" );
$total = $db->fetch_array( $query );
$total = $total['c'];
pageft( $total, 10 );
if ( $firstcount < 0 )
{
		$firstcount = 0;
}
$query = $db->select( "users", "*", "user_power=6 {$user_limit} limit {$firstcount}, {$displaypg}" );
$user_char = "会员";
$power = 6;
echo "<html oncontextmenu=\"return false\" xmlns=\"http://www.w3.org/1999/xhtml\"><head>\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=gbk\"></head>\n    \n<body>\n<link href=\"../images/Index.css\" rel=\"stylesheet\" type=\"text/css\">\n    ";
echo "<s";
echo "tyle>\n        .xxx{\n            background-image: none;\n            background-color: white;\n        }\n        .xxx td{\n            background: none;\n        }\n    </style>\n";
echo "<s";
echo "cript src=\"../js/jquery-1.4.3.min.js\" type=\"text/javascript\"></script>\n";
echo "<s";
echo "cript src=\"js/normal.js\" type=\"text/javascript\"></script>\n";
echo "<s";
echo "cript type=\"text/javascript\">\nvar power=6;\nvar page=";
echo $_GET['page'] ? $_GET['page'] : 1;
echo ";\nvar t0=\"";
echo $_GET['get_user_limit'] ? $_GET['get_user_limit'] : 0;
echo "\";\nfunction C_Key(){\n        var t1=\$(\"#vip_name\").val();\n        var t2=\$(\"#vip_selectl\").val();\n        window.location.href=\"member.php?t1=\"+t1+\"&t2=\"+t2+\"&power=\"+power+\"&page=1&get_user_limit=\"+t0;\n}\n\nfunction get_user_limit(th){\n    window.location.href=\"member.php?get_user_limit=\"+th+\"&power=\"+power+\"&page=1\";\n}\n</script>\n <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\n  <tbod";
echo "y>\n    <tr>\n      <td background=\"../images/tab_05.gif\" height=\"30\"><table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\n        <tbody>\n          <tr>\n            <td height=\"30\" width=\"12\"><img src=\"../images/tab_03.gif\" height=\"30\" width=\"12\"></td>\n            <td><table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\n              <tbody>\n                <tr>\n                  <td valig";
echo "n=\"middle\" width=\"87%\"><table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\n                    <tbody>\n                      <tr>\n                              <td width=\"1%\"><div align=\"center\"><img src=\"../images/tb.gif\" height=\"16\" width=\"16\"></div></td>\n                              <td class=\"F_bold\" width=\"32%\">";
echo "<s";
echo "pan id=\"ftm1\">";
echo $user_char;
echo "</span>管理</td>\n                              <td class=\"F_bold\" align=\"right\" nowrap=\"nowrap\" width=\"45\">篩選：</td>\n                              <td nowrap=\"nowrap\">";
echo "<s";
echo "elect name=\"VIP_Estate\" onChange=\"get_user_limit(\$(this).val());\">\n                                  <option value=\"0\" ";
echo $get_user_limit == 0 ? "selected='selected'" : "";
echo ">全部</option>\n                                  <option value=\"1\" ";
echo $get_user_limit == 1 ? "selected='selected'" : "";
echo ">啟用</option>\n                                  <option value=\"3\" ";
echo $get_user_limit == 3 ? "selected='selected'" : "";
echo ">凍結</option>\n                                  <option value=\"2\" ";
echo $get_user_limit == 2 ? "selected='selected'" : "";
echo ">停用 </option>\n                                </select>\n                                &nbsp;&nbsp;</td>\n                              <td class=\"F_bold\" align=\"right\" nowrap=\"nowrap\" width=\"45\">搜索：</td>\n                              <td nowrap=\"nowrap\">\n                                  ";
echo "<s";
echo "elect id=\"vip_name\" name=\"VIP_name\" onChange=\"return C_Key();\">\n                                  <option ";
echo $t1 == 0 ? "selected='selected'" : "";
echo " value=\"0\">帳號：</option>\n                                  <option ";
echo $t1 == 1 ? "selected='selected'" : "";
echo " value=\"1\">名稱：</option>\n                                </select></td>\n                              \n                              <td class=\"F_bold\" width=\"67%\"><input value=\"";
echo $t2;
echo "\" name=\"key\" id=\"vip_selectl\" class=\"input1\" onBlur=\"return C_Key();\" type=\"text\">\n                                <input name=\"xctype\" id=\"xctype\" value=\"Czc!888\" type=\"hidden\"></td>\n                              <td class=\"F_bold\" align=\"right\" nowrap=\"nowrap\" ><a href=\"addbranch.php?power=6\" class=\"button_a\">新增会员</a></td>\n                              \n                      </tr>\n                 ";
echo "   </tbody>\n                  </table></td>\n                  </tr>\n              </tbody>\n            </table></td>\n            <td width=\"16\"><img src=\"../images/tab_07.gif\" height=\"30\" width=\"16\"></td>\n          </tr>\n        </tbody>\n      </table></td>\n    </tr>\n    <tr>\n      <td><table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\n        <tbody>\n          <tr>\n            <td background=\"../images/t";
echo "ab_12.gif\" width=\"8\">&nbsp;</td>\n            <td align=\"center\" height=\"50\"><!-- 開始  --><div id=\"result\">\n\n\t\t\t    <input name=\"fm33\" value=\"\" type=\"hidden\">\n            <table class=\"Ball_List\" align=\"center\" bgcolor=\"ffffff\" border=\"0\" bordercolor=\"f1f1f1\" cellpadding=\"1\" cellspacing=\"1\" width=\"99%\">\n                          <tbody>\n                              <tr class=\"td_caption_1\">\n             ";
echo "               <td bordercolor=\"cccccc\" bgcolor=\"#DFEFFF\" nowrap=\"nowrap\" width=\"50\"><div align=\"center\">\n                              在線\n                          </div></td>\n                            <td bordercolor=\"cccccc\" bgcolor=\"#DFEFFF\" nowrap=\"nowrap\" width=\"50\">會員類型</td>                            <td bordercolor=\"cccccc\" bgcolor=\"#DFEFFF\" nowrap=\"nowrap\"><div align=\"center\">用戶</div></t";
echo "d>\n                            <td bordercolor=\"cccccc\" align=\"center\" bgcolor=\"#DFEFFF\" nowrap=\"nowrap\">名稱</td>\n                            <td bordercolor=\"cccccc\" align=\"center\" bgcolor=\"#DFEFFF\" nowrap=\"nowrap\">信用額度/余額</td>\n\t\t\t\t\t\t\t                            <td bordercolor=\"cccccc\" bordercolordark=\"#FFFFFF\" align=\"center\" bgcolor=\"#DFEFFF\" nowrap=\"NOWRAP\">代理</td>\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t          ";
echo "                  <td bordercolor=\"cccccc\" bordercolordark=\"#FFFFFF\" align=\"center\" bgcolor=\"#DFEFFF\" nowrap=\"NOWRAP\">總代理</td>\n\t\t\t\t\t\t\t                            <td bordercolor=\"cccccc\" bordercolordark=\"#FFFFFF\" align=\"center\" bgcolor=\"#DFEFFF\" nowrap=\"NOWRAP\">股東</td>\n\t\t\t\t\t\t\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t                            <td bordercolor=\"cccccc\" bordercolordark=\"#FFFFFF\" align=\"center\" bgcolor=\"#DFEF";
echo "FF\" nowrap=\"NOWRAP\">分公司</td>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t                            <td bordercolor=\"cccccc\" bordercolordark=\"#FFFFFF\" align=\"center\" bgcolor=\"#DFEFFF\" nowrap=\"NOWRAP\">代理%</td>\n\t\t\t\t\t\t\t                            <td bordercolor=\"cccccc\" bordercolordark=\"#FFFFFF\" align=\"center\" bgcolor=\"#DFEFFF\" nowrap=\"NOWRAP\">總代理%</td>\n\t\t\t\t\t\t\t                            <td bordercolo";
echo "r=\"cccccc\" bordercolordark=\"#FFFFFF\" align=\"center\" bgcolor=\"#DFEFFF\" nowrap=\"NOWRAP\">股東%</td>\n\t\t\t\t\t\t\t                            <td bordercolor=\"cccccc\" bordercolordark=\"#FFFFFF\" align=\"center\" bgcolor=\"#DFEFFF\" nowrap=\"nowrap\">分公司%</td>\n\t\t\t\t\t\t\t                            <td bordercolor=\"cccccc\" bordercolordark=\"#FFFFFF\" align=\"center\" bgcolor=\"#DFEFFF\" nowrap=\"nowrap\">公司%</td>\n              ";
echo "              <td bordercolor=\"cccccc\" bordercolordark=\"#FFFFFF\" align=\"center\" bgcolor=\"#DFEFFF\" nowrap=\"nowrap\">類型</td>\n                            <td bordercolor=\"cccccc\" align=\"center\" bgcolor=\"#DFEFFF\" nowrap=\"nowrap\">註冊時間</td>\n                            <td bordercolor=\"cccccc\" align=\"center\" bgcolor=\"#DFEFFF\" nowrap=\"nowrap\">登錄次数</td>\n                            <td bordercolor=\"cccccc";
echo "\" align=\"center\" bgcolor=\"#DFEFFF\" nowrap=\"nowrap\">停押</td>\n                            <td bordercolor=\"cccccc\" align=\"center\" bgcolor=\"#DFEFFF\" nowrap=\"nowrap\">狀況</td>\n\t\t\t\t\t\t\t                            <td bordercolor=\"cccccc\" bgcolor=\"#DFEFFF\" nowrap=\"NOWRAP\"><div align=\"center\">操作\n\t\t\t\t\t\t    </div></td>\n                          </tr>\n\t\t\t\t\t\t  \n ";
while ( $row = $db->fetch_array( $query ) )
{
		echo "                          \n<tr class=\"td_caption_1 xxx\">\n                            <td bordercolor=\"cccccc\" height=\"25\"><div align=\"center\">\n                                <img src=\"../images/USER_0.gif\">\n                            </div></td>\n                             <td bordercolor=\"cccccc\" align=\"center\">";
		echo $row['is_directly'] == 1 ? "直属会员" : "普通会员";
		echo "</td>                            \n                             <td align=\"center\" height=\"25\">";
		echo $row['user_name'];
		echo "</td>\n                            <td align=\"center\" height=\"25\">";
		echo $row['user_nick'];
		echo "</td>\n                            <td align=\"center\" height=\"25\" nowrap=\"nowrap\">";
		echo $row['credit_total'];
		echo "/";
		echo $row['credit_remainder'];
		echo "</td>\n";
		$his_top = $db->get_his_top( $row['is_directly'], $row['top_id'], $row['top_name'] );
		echo "                            <td bordercolor=\"cccccc\" bordercolordark=\"#FFFFFF\" align=\"center\"><a href=\"#\">";
		echo $his_top['proxy'];
		echo "</a></td>\n                            <td bordercolor=\"cccccc\" bordercolordark=\"#FFFFFF\" align=\"center\"><a href=\"#\">";
		echo $his_top['all_proxy'];
		echo "</a></td>\n                            <td bordercolor=\"cccccc\" bordercolordark=\"#FFFFFF\" align=\"center\"><a href=\"#\">";
		echo $his_top['partner'];
		echo "</a></td>\n                            <td bordercolor=\"cccccc\" bordercolordark=\"#FFFFFF\" align=\"center\"><a href=\"#\">";
		echo $his_top['branch'];
		echo "</a></td>\n\t\t\t\t\t\t\t                         \t\t\t\t\t\n                            <td bordercolor=\"cccccc\" bordercolordark=\"#FFFFFF\" align=\"center\">";
		echo $row['percent_proxy'];
		echo " %</td>\n                            <td bordercolor=\"cccccc\" bordercolordark=\"#FFFFFF\" align=\"center\">";
		echo $row['percent_all_proxy'];
		echo " %</td>\n                            <td bordercolor=\"cccccc\" bordercolordark=\"#FFFFFF\" align=\"center\">";
		echo $row['percent_partner'];
		echo " %</td>\n                            <td bordercolor=\"cccccc\" bordercolordark=\"#FFFFFF\" align=\"center\" height=\"25\">";
		echo $row['percent_branch'];
		echo "%</td>\n                            <td bordercolor=\"cccccc\" bordercolordark=\"#FFFFFF\" align=\"center\">";
		echo $row['percent_company'];
		echo " %</td>\n                            \n                        <td bordercolor=\"cccccc\" bordercolordark=\"#FFFFFF\" align=\"center\" nowrap=\"nowrap\">";
		echo $row['else_plate'];
		echo "盤</td>\n                            <td align=\"center\" height=\"25\">";
		echo $row['else_created_at'];
		echo "</td>\n                            <td align=\"center\" width=\"60\">";
		echo "<s";
		echo "pan>";
		echo $row['else_count_login'];
		echo "</span></td>\n                            <td align=\"center\">\n                            <input type=\"hidden\" value=\"";
		echo $row['is_odds'];
		echo "\" />\n                            <button class=\"button_a\" onClick=\"set_is(\$(this),1,";
		echo $row['user_id'];
		echo ")\"> ";
		echo $row['is_odds'] == 0 ? "已開啟" : "<font color='ff0000'>禁止</font>";
		echo " </button></td>\n                        <td align=\"center\" height=\"25\">\n                            <input type=\"hidden\" value=\"";
		echo $row['is_lock'];
		echo "\" />\n                            <button class=\"button_a\" onClick=\"set_is(\$(this),2,";
		echo $row['user_id'];
		echo ")\">";
		echo $row['is_lock'] == 0 ? "已開啟" : "<font color='ff0000'>禁止</font>";
		echo "</button></td>\n                        \n<td nowrap=\"nowrap\"><div align=\"center\">\n                              \n<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n<tbody>\n    <tr valign=\"bottom\">\n        <td height=\"18\" nowrap=\"nowrap\" width=\"14\"><img src=\"../images/edt.gif\"></td>\n        <td nowrap=\"nowrap\" width=\"30\"><a href=\"reback.php?power=";
		echo "6&user_id=".$row['user_id'];
		echo "\"  target=\"content\">退水</a></td>\n        <td height=\"18\" nowrap=\"nowrap\" width=\"15\"><img src=\"../images/edit.gif\" height=\"15\" width=\"14\"></td>\n        <td nowrap=\"nowrap\" width=\"30\"><a href=\"update_mes.php?power=6";
		echo "&user_id=".$row['user_id'];
		echo "\"  target=\"content\">修改</a></td>\n        <td nowrap=\"nowrap\" width=\"16\"><img src=\"../images/55.gif\"></td>\n        <td nowrap=\"nowrap\" width=\"30\"><a href=\"user_log.php?user_id=";
		echo $row['user_id']."&user_name=".$row['user_name'];
		echo "\"  target=\"content\">日誌</a></td>\n        <td nowrap=\"nowrap\" width=\"16\"><img src=\"../images/44.gif\"></td>\n        <td nowrap=\"nowrap\" width=\"26\"><a href=\"mark.php?user_id=";
		echo $row['user_id']."&user_name=".$row['user_name'];
		echo "\"  target=\"content\">記錄</a></td>\n        <td nowrap=\"nowrap\" width=\"16\"><img src=\"../images/icon_21x21_del.gif\" height=\"14\" width=\"14\"></td>\n        <td nowrap=\"nowrap\" width=\"26\"><a href=\"delete_user.php?power=";
		echo "6&id=".$row['user_id'];
		echo "\" onclick='{if(confirm(\"您確定刪除嗎?此操作將不能恢復!\")){ return true;}else{return   false;}}' >刪除</a></td>\n    </tr>\n</tbody>\n</table>\n\n\n</div></td>\n                          </tr>\n   ";
}
echo "                        \n<tr class=\"td_caption_1 xxx\">\n    ";
echo $pagenav;
echo "</tr>\n                        \n                  </tbody></table>\n            \n             \n\n</div> <!-- 結束  --></td>\n            <td background=\"../images/tab_15.gif\" width=\"8\">&nbsp;</td>\n          </tr>\n        </tbody>\n      </table></td>\n    </tr>\n    <tr>\n      <td background=\"../images/tab_19.gif\" height=\"35\"><table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\n        <tbody>\n          <tr>\n  ";
echo "          <td height=\"35\" width=\"12\"><img src=\"../images/tab_18.gif\" height=\"35\" width=\"12\"></td>\n            <td valign=\"top\"><table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" height=\"30\" width=\"100%\">\n              <tbody>\n                <tr>\n                  <td align=\"center\">&nbsp;</td>\n                </tr>\n              </tbody>\n            </table></td>\n            <td width=\"16\"><img src=\"../images/ta";
echo "b_20.gif\" height=\"35\" width=\"16\"></td>\n          </tr>\n        </tbody>\n      </table></td>\n    </tr>\n  </tbody>\n</table>\n<div id=\"ly\" style=\"position: absolute; top: 0px; filter: alpha(opacity=70); background-color: #ffffff;\nz-index: 2; left: 0px; display: none;\">\n <!--[if lte IE 6.5]><iframe></iframe><![endif]-->\n</div>\n<!--          浮層框架開始         -->\n<div id=\"rs_window\" style=\"position: absolute; top: 0";
echo "px; \nz-index: 2000; left: 0px; display: none;\">\n</div>\n\n</body></html>";
?>
