<?php
function set( $name, $uid )
{
		$sql = "select * from back_set where set_name = '{$name}' and user_id = '{$uid}'";
		$bs = mysql_query( $sql );
		while ( $bs_info = mysql_fetch_array( $bs ) )
		{
				$bs_detail[] = array(
						"bottom_limit" => $bs_info['bottom_limit'],
						"top_limit" => $bs_info['top_limit'],
						"odd_limit" => $bs_info['odd_limit']
				);
		}
		return $bs_detail;
}

include_once( "../../global.php" );
$db = new plate( $mydbhost, $mydbuser, $mydbpw, $mydbname, ALL_PS, $mydbcharset );
$uid = $zizhanghaodenglu[1];
$username = $_SESSION["username".$c_p_seesion];
$info = mysql_fetch_array( mysql_query( "select * from users  where user_id = '{$uid}'" ) );
echo "<html oncontextmenu=\"return false\" xmlns=\"http://www.w3.org/1999/xhtml\"><head>\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n";
echo "<s";
echo "tyle type=\"text/css\">\n<!--\nbody {\n\tmargin-left: 0px;\n\tmargin-top: 0px;\n\tmargin-right: 0px;\n\tmargin-bottom: 0px;\n}\n-->\n</style>\n</head>\n<body onmouseover=\"self.status='歡迎光臨';return true\">\n<link href=\"../images/Index.css\" rel=\"stylesheet\" type=\"text/css\">\n \n";
echo "<s";
echo "tyle type=\"text/css\">\n<!--\n.style1 {\n\tcolor: #666666;\n\tfont-weight: bold;\n}\n.style2 {color: #FF0000}\n.STYLE4 {\n\tcolor: #000000;\n\tfont-weight: bold;\n}\n-->\n</style>\n\n<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\n <tbody>\n    <tr>\n      <td background=\"../images/tab_05.gif\" height=\"30\"><table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\n        <tbody>\n          <tr>\n            ";
echo "<td height=\"30\" width=\"12\"><img src=\"../images/tab_03.gif\" height=\"30\" width=\"12\"></td>\n            <td><table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\n              <tbody>\n                <tr>\n                  <td valign=\"middle\" width=\"87%\"><table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\n                    <tbody>\n                      <tr>\n                        <td widt";
echo "h=\"16\"><div align=\"center\"><img src=\"../images/tb.gif\" height=\"16\" width=\"16\"></div></td>\n                        <td class=\"F_bold\" width=\"151\">信用資料</td>\n                        <td class=\"F_bold\" align=\"right\" nowrap=\"nowrap\">&nbsp;</td>\n       \n<td class=\"F_bold\" width=\"839\"> \n\t\t\t\t\t\t  </td>\n                        <td class=\"F_bold\" width=\"12\">&nbsp;</td>\n                      <td align=\"right\" width=\"1";
echo "79\">&#59312; </td>\n                      </tr>\n                    </tbody>\n                  </table></td>\n                  </tr>\n              </tbody>\n            </table></td>\n            <td width=\"16\"><img src=\"../images/tab_07.gif\" height=\"30\" width=\"16\"></td>\n          </tr>\n        </tbody>\n      </table></td>\n    </tr>\n    <tr>\n      <td><table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\n     ";
echo "   <tbody>\n          <tr>\n            <td background=\"../images/tab_12.gif\" width=\"8\">&nbsp;</td>\n            ";
if ( 0 < $info['is_extend'] )
{
		echo "            <TD height=50 align=center><!-- 開始  -->\n            <DIV id=result>\n            <TABLE class=Ball_List border=0 cellSpacing=1 cellPadding=0 \n            width=\"100%\">\n              <TBODY>\n              <TR>\n                <TD bgColor=#dfefff height=30 borderColor=#cccccc width=\"17%\" \n                align=right>子賬號：</TD>\n                <TD bgColor=#ffffff borderColor=#cccccc width=\"83%";
		echo "\">";
		echo $info['user_name'];
		echo "</TD></TR>\n              <TR>\n                <TD bgColor=#dfefff height=30 borderColor=#cccccc \n                  align=right>";
		echo "<S";
		echo "PAN class=t_Edit_caption>子賬號名称</SPAN>：</TD>\n                <TD bgColor=#ffffff borderColor=#cccccc>";
		echo $info['user_nick'];
		echo " \n            </TD></TR></TBODY></TABLE></DIV><!-- 結束  --></TD>\n            ";
}
else
{
		echo "            <td align=\"center\" height=\"50\"><!-- 開始  --><div id=\"result\">              <table class=\"Ball_List\" border=\"0\" cellpadding=\"0\" cellspacing=\"1\" width=\"100%\">\n\n   <tbody><tr>\n    <td bordercolor=\"#CCCCCC\" align=\"right\" bgcolor=\"#DFEFFF\" height=\"30\" width=\"17%\">賬號：</td>\n    <td bordercolor=\"#CCCCCC\" bgcolor=\"#FFFFFF\" width=\"83%\">\n      ";
		echo $username;
		echo "(\n       ";
		echo trim( $info['else_plate'], "," );
		echo "   盤   )</td>\n    </tr>\n  <tr>\n    <td bordercolor=\"#CCCCCC\" align=\"right\" bgcolor=\"#DFEFFF\" height=\"30\">總信用額：</td>\n    <td bordercolor=\"#CCCCCC\" bgcolor=\"#FFFFFF\">";
		echo $info['credit_total'];
		echo "     </td>\n    </tr>\n  <tr>\n    <td bordercolor=\"#CCCCCC\" align=\"right\" bgcolor=\"#DFEFFF\" height=\"30\">下注余額：</td>\n    <td bordercolor=\"#CCCCCC\" bgcolor=\"#FFFFFF\">\n      ";
		echo $info['credit_remainder'];
		echo "    </td>\n    </tr>\n</tbody></table>\n \n<table class=\"Ball_List\" border=\"0\" bordercolor=\"f1f1f1\" cellpadding=\"0\" cellspacing=\"1\" width=\"100%\">\n  <tbody><tr class=\"td_caption_1\">\n    <td align=\"center\" bgcolor=\"#DFEFFF\" width=\"90\">交易類型</td>\n        <td align=\"center\" bgcolor=\"#DFEFFF\">最低限額</td>\n   \n    <td align=\"center\" bgcolor=\"#DFEFFF\">最高限額</td>\n    <td align=\"center\" bgcolor=\"#DFEFFF\">单項(號)限額";
		echo "</td>\n\t\n\t<td align=\"center\" bgcolor=\"#DFEFFF\" width=\"90\">交易類型</td>\n        <td align=\"center\" bgcolor=\"#DFEFFF\">最低限額</td>\n   \n    <td align=\"center\" bgcolor=\"#DFEFFF\">最高限額</td>\n    <td align=\"center\" bgcolor=\"#DFEFFF\">单項(號)限額</td>\n  </tr>\n  \n    <tr>\n    <td align=\"center\" bgcolor=\"#DFEFFF\" height=\"20\">特码A</td>\n    ";
		$info = set( "特码A", $uid );
		echo "    <td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info[0]['bottom_limit'];
		echo "</td>\n  \t<td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info[0]['top_limit'];
		echo "</td>\n    <td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info[0]['odd_limit'];
		echo "</td>\n\t\n\t\n\t   <td align=\"center\" bgcolor=\"#DFEFFF\" height=\"20\">特码B</td>\n       ";
		$info1 = set( "特码B", $uid );
		echo "        <td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info1[0]['bottom_limit'];
		echo "</td>\n  \t<td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info1[0]['top_limit'];
		echo "</td>\n    <td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info1[0]['odd_limit'];
		echo "</td>\n  </tr>\n  \n    <tr>\n    <td align=\"center\" bgcolor=\"#DFEFFF\" height=\"20\">正1特A</td>\n        ";
		$info2 = set( "正1特A", $uid );
		echo "        <td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info2[0]['bottom_limit'];
		echo "</td>\n  \t<td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info2[0]['top_limit'];
		echo "</td>\n    <td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info2[0]['odd_limit'];
		echo "</td>\n\t\n\t\n\t   <td align=\"center\" bgcolor=\"#DFEFFF\" height=\"20\">正1特B</td>\n        ";
		$info3 = set( "正1特B", $uid );
		echo "        <td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info3[0]['bottom_limit'];
		echo "</td>\n  \t<td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info3[0]['top_limit'];
		echo "</td>\n    <td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info3[0]['odd_limit'];
		echo "</td>\n  </tr>\n    <tr>\n    <td align=\"center\" bgcolor=\"#DFEFFF\" height=\"20\">正2特A</td>\n       ";
		$info4 = set( "正2特A", $uid );
		echo "        <td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info4[0]['bottom_limit'];
		echo "</td>\n  \t<td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info4[0]['top_limit'];
		echo "</td>\n    <td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info4[0]['odd_limit'];
		echo "</td>\n\t\n\t\n\t   <td align=\"center\" bgcolor=\"#DFEFFF\" height=\"20\">正2特B</td>\n        ";
		$info5 = set( "正2特B", $uid );
		echo "        <td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info5[0]['bottom_limit'];
		echo "</td>\n  \t<td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info5[0]['top_limit'];
		echo "</td>\n    <td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info5[0]['odd_limit'];
		echo "</td>\n  </tr>\n    <tr>\n    <td align=\"center\" bgcolor=\"#DFEFFF\" height=\"20\">正3特A</td>\n        ";
		$info6 = set( "正3特A", $uid );
		echo "        <td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info6[0]['bottom_limit'];
		echo "</td>\n  \t<td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info6[0]['top_limit'];
		echo "</td>\n    <td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info6[0]['odd_limit'];
		echo "</td>\n\t\n\t\n\t   <td align=\"center\" bgcolor=\"#DFEFFF\" height=\"20\">正3特B</td>\n        ";
		$info7 = set( "正3特B", $uid );
		echo "        <td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info7[0]['bottom_limit'];
		echo "</td>\n  \t<td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info7[0]['top_limit'];
		echo "</td>\n    <td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info7[0]['odd_limit'];
		echo "</td>\n  </tr>\n    <tr>\n    <td align=\"center\" bgcolor=\"#DFEFFF\" height=\"20\">正4特A</td>\n        ";
		$info8 = set( "正4特A", $uid );
		echo "        <td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info8[0]['bottom_limit'];
		echo "</td>\n  \t<td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info8[0]['top_limit'];
		echo "</td>\n    <td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info8[0]['odd_limit'];
		echo "</td>\n\t\n\t\n\t   <td align=\"center\" bgcolor=\"#DFEFFF\" height=\"20\">正4特B</td>\n        ";
		$info9 = set( "正4特B", $uid );
		echo "        <td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info9[0]['bottom_limit'];
		echo "</td>\n  \t<td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info9[0]['top_limit'];
		echo "</td>\n    <td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info9[0]['odd_limit'];
		echo "</td>\n  </tr>\n    <tr>\n    <td align=\"center\" bgcolor=\"#DFEFFF\" height=\"20\">正5特A</td>\n        ";
		$info10 = set( "正5特A", $uid );
		echo "        <td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info10[0]['bottom_limit'];
		echo "</td>\n  \t<td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info10[0]['top_limit'];
		echo "</td>\n    <td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info10[0]['odd_limit'];
		echo "</td>\n\t\n\t\n\t   <td align=\"center\" bgcolor=\"#DFEFFF\" height=\"20\">正5特B</td>\n        ";
		$info11 = set( "正5特B", $uid );
		echo "        <td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info11[0]['bottom_limit'];
		echo "</td>\n  \t<td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info11[0]['top_limit'];
		echo "</td>\n    <td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info11[0]['odd_limit'];
		echo "</td>\n  </tr>\n    <tr>\n    <td align=\"center\" bgcolor=\"#DFEFFF\" height=\"20\">正6特A</td>\n       ";
		$info12 = set( "正6特A", $uid );
		echo "        <td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info12[0]['bottom_limit'];
		echo "</td>\n  \t<td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info12[0]['top_limit'];
		echo "</td>\n    <td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info12[0]['odd_limit'];
		echo "</td>\n\t\n\t\n\t   <td align=\"center\" bgcolor=\"#DFEFFF\" height=\"20\">正6特B</td>\n        ";
		$info13 = set( "正6特B", $uid );
		echo "        <td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info13[0]['bottom_limit'];
		echo "</td>\n  \t<td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info13[0]['top_limit'];
		echo "</td>\n    <td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info13[0]['odd_limit'];
		echo "</td>\n  </tr>\n    <tr>\n    <td align=\"center\" bgcolor=\"#DFEFFF\" height=\"20\">正码A</td>\n        ";
		$info14 = set( "正码A", $uid );
		echo "        <td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info14[0]['bottom_limit'];
		echo "</td>\n  \t<td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info14[0]['top_limit'];
		echo "</td>\n    <td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info14[0]['odd_limit'];
		echo "</td>\n\t\n\t\n\t   <td align=\"center\" bgcolor=\"#DFEFFF\" height=\"20\">正码B</td>\n        ";
		$info15 = set( "正码B", $uid );
		echo "        <td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info15[0]['bottom_limit'];
		echo "</td>\n  \t<td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info15[0]['top_limit'];
		echo "</td>\n    <td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info15[0]['odd_limit'];
		echo "</td>\n  </tr>\n    <tr>\n    <td align=\"center\" bgcolor=\"#DFEFFF\" height=\"20\">两面</td>\n        ";
		$info16 = set( "两面", $uid );
		echo "        <td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info16[0]['bottom_limit'];
		echo "</td>\n  \t<td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info16[0]['top_limit'];
		echo "</td>\n    <td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info16[0]['odd_limit'];
		echo "</td>\n\t\n\t\n\t   <td align=\"center\" bgcolor=\"#DFEFFF\" height=\"20\">波色</td>\n       ";
		$info17 = set( "波色", $uid );
		echo "        <td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info17[0]['bottom_limit'];
		echo "</td>\n  \t<td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info17[0]['top_limit'];
		echo "</td>\n    <td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info17[0]['odd_limit'];
		echo "</td>\n  </tr>\n    <tr>\n    <td align=\"center\" bgcolor=\"#DFEFFF\" height=\"20\">特肖</td>\n        ";
		$info18 = set( "特肖", $uid );
		echo "        <td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info18[0]['bottom_limit'];
		echo "</td>\n  \t<td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info18[0]['top_limit'];
		echo "</td>\n    <td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info18[0]['odd_limit'];
		echo "</td>\n\t\n\t\n\t   <td align=\"center\" bgcolor=\"#DFEFFF\" height=\"20\">二肖</td>\n         ";
		$info19 = set( "二肖", $uid );
		echo "        <td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info19[0]['bottom_limit'];
		echo "</td>\n  \t<td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info19[0]['top_limit'];
		echo "</td>\n    <td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info19[0]['odd_limit'];
		echo "</td>\n  </tr>\n    <tr>\n    <td align=\"center\" bgcolor=\"#DFEFFF\" height=\"20\">三肖</td>\n         ";
		$info20 = set( "三肖", $uid );
		echo "        <td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info20[0]['bottom_limit'];
		echo "</td>\n  \t<td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info20[0]['top_limit'];
		echo "</td>\n    <td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info20[0]['odd_limit'];
		echo "</td>\n\t\n\t\n\t   <td align=\"center\" bgcolor=\"#DFEFFF\" height=\"20\">四肖</td>\n        ";
		$info21 = set( "四肖", $uid );
		echo "        <td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info21[0]['bottom_limit'];
		echo "</td>\n  \t<td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info21[0]['top_limit'];
		echo "</td>\n    <td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info21[0]['odd_limit'];
		echo "</td>\n  </tr>\n    <tr>\n    <td align=\"center\" bgcolor=\"#DFEFFF\" height=\"20\">五肖</td>\n        ";
		$info22 = set( "五肖", $uid );
		echo "        <td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info22[0]['bottom_limit'];
		echo "</td>\n  \t<td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info22[0]['top_limit'];
		echo "</td>\n    <td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info22[0]['odd_limit'];
		echo "</td>\n\t\n\t\n\t   <td align=\"center\" bgcolor=\"#DFEFFF\" height=\"20\">六肖</td>\n        ";
		$info23 = set( "六肖", $uid );
		echo "        <td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info23[0]['bottom_limit'];
		echo "</td>\n  \t<td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info23[0]['top_limit'];
		echo "</td>\n    <td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info23[0]['odd_limit'];
		echo "</td>\n  </tr>\n    <tr>\n    <td align=\"center\" bgcolor=\"#DFEFFF\" height=\"20\">一肖</td>\n       ";
		$info24 = set( "一肖", $uid );
		echo "        <td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info24[0]['bottom_limit'];
		echo "</td>\n  \t<td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info24[0]['top_limit'];
		echo "</td>\n    <td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info24[0]['odd_limit'];
		echo "</td>\n\t\n\t\n\t   <td align=\"center\" bgcolor=\"#DFEFFF\" height=\"20\">尾数</td>\n       ";
		$info25 = set( "尾数", $uid );
		echo "        <td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info25[0]['bottom_limit'];
		echo "</td>\n  \t<td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info25[0]['top_limit'];
		echo "</td>\n    <td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info25[0]['odd_limit'];
		echo "</td>\n  </tr>\n    <tr>\n    <td align=\"center\" bgcolor=\"#DFEFFF\" height=\"20\">生肖连</td>\n        ";
		$info26 = set( "生肖连", $uid );
		echo "        <td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info26[0]['bottom_limit'];
		echo "</td>\n  \t<td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info26[0]['top_limit'];
		echo "</td>\n    <td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info26[0]['odd_limit'];
		echo "</td>\n\t\n\t\n\t   <td align=\"center\" bgcolor=\"#DFEFFF\" height=\"20\">尾数连</td>\n        ";
		$info27 = set( "尾数连", $uid );
		echo "        <td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info27[0]['bottom_limit'];
		echo "</td>\n  \t<td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info27[0]['top_limit'];
		echo "</td>\n    <td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info27[0]['odd_limit'];
		echo "</td>\n  </tr>\n    <tr>\n    <td align=\"center\" bgcolor=\"#DFEFFF\" height=\"20\">五不中</td>\n        ";
		$info28 = set( "五不中", $uid );
		echo "        <td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info28[0]['bottom_limit'];
		echo "</td>\n  \t<td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info28[0]['top_limit'];
		echo "</td>\n    <td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info28[0]['odd_limit'];
		echo "</td>\n\t\n\t\n\t   <td align=\"center\" bgcolor=\"#DFEFFF\" height=\"20\">六不中</td>\n        ";
		$info29 = set( "六不中", $uid );
		echo "        <td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info29[0]['bottom_limit'];
		echo "</td>\n  \t<td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info29[0]['top_limit'];
		echo "</td>\n    <td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info29[0]['odd_limit'];
		echo "</td>\n  </tr>\n    <tr>\n    <td align=\"center\" bgcolor=\"#DFEFFF\" height=\"20\">七不中</td>\n        ";
		$info30 = set( "七不中", $uid );
		echo "        <td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info30[0]['bottom_limit'];
		echo "</td>\n  \t<td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info30[0]['top_limit'];
		echo "</td>\n    <td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info30[0]['odd_limit'];
		echo "</td>\n\t\n\t\n\t   <td align=\"center\" bgcolor=\"#DFEFFF\" height=\"20\">八不中</td>\n        ";
		$info31 = set( "八不中", $uid );
		echo "        <td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info31[0]['bottom_limit'];
		echo "</td>\n  \t<td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info31[0]['top_limit'];
		echo "</td>\n    <td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info31[0]['odd_limit'];
		echo "</td>\n  </tr>\n    <tr>\n    <td align=\"center\" bgcolor=\"#DFEFFF\" height=\"20\">九不中</td>\n        ";
		$info32 = set( "九不中", $uid );
		echo "        <td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info32[0]['bottom_limit'];
		echo "</td>\n  \t<td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info32[0]['top_limit'];
		echo "</td>\n    <td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info32[0]['odd_limit'];
		echo "</td>\n\t\n\t\n\t   <td align=\"center\" bgcolor=\"#DFEFFF\" height=\"20\">十不中</td>\n        ";
		$info33 = set( "十不中", $uid );
		echo "        <td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info33[0]['bottom_limit'];
		echo "</td>\n  \t<td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info33[0]['top_limit'];
		echo "</td>\n    <td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info33[0]['odd_limit'];
		echo "</td>\n  </tr>\n    <tr>\n    <td align=\"center\" bgcolor=\"#DFEFFF\" height=\"20\">半波</td>\n        ";
		$info34 = set( "半波", $uid );
		echo "        <td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info34[0]['bottom_limit'];
		echo "</td>\n  \t<td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info34[0]['top_limit'];
		echo "</td>\n    <td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info34[0]['odd_limit'];
		echo "</td>\n\t\n\t\n\t   <td align=\"center\" bgcolor=\"#DFEFFF\" height=\"20\">过关</td>\n        ";
		$info35 = set( "过关", $uid );
		echo "        <td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info35[0]['bottom_limit'];
		echo "</td>\n  \t<td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info35[0]['top_limit'];
		echo "</td>\n    <td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info35[0]['odd_limit'];
		echo "</td>\n  </tr>\n    <tr>\n    <td align=\"center\" bgcolor=\"#DFEFFF\" height=\"20\">二全中</td>\n        ";
		$info36 = set( "二全中", $uid );
		echo "        <td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info36[0]['bottom_limit'];
		echo "</td>\n  \t<td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info36[0]['top_limit'];
		echo "</td>\n    <td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info36[0]['odd_limit'];
		echo "</td>\n\t\n\t\n\t   <td align=\"center\" bgcolor=\"#DFEFFF\" height=\"20\">二中特</td>\n         ";
		$info37 = set( "二中特", $uid );
		echo "        <td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info37[0]['bottom_limit'];
		echo "</td>\n  \t<td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info37[0]['top_limit'];
		echo "</td>\n    <td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info37[0]['odd_limit'];
		echo "</td>\n  </tr>\n    <tr>\n    <td align=\"center\" bgcolor=\"#DFEFFF\" height=\"20\">特串</td>\n         ";
		$info38 = set( "特串", $uid );
		echo "        <td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info38[0]['bottom_limit'];
		echo "</td>\n  \t<td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info38[0]['top_limit'];
		echo "</td>\n    <td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info38[0]['odd_limit'];
		echo "</td>\n\t\n\t\n\t   <td align=\"center\" bgcolor=\"#DFEFFF\" height=\"20\">三全中</td>\n         ";
		$info39 = set( "三全中", $uid );
		echo "        <td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info39[0]['bottom_limit'];
		echo "</td>\n  \t<td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info39[0]['top_limit'];
		echo "</td>\n    <td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info39[0]['odd_limit'];
		echo "</td>\n  </tr>\n    <tr>\n    <td align=\"center\" bgcolor=\"#DFEFFF\" height=\"20\">三中二</td>\n        ";
		$info40 = set( "三中二", $uid );
		echo "        <td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info40[0]['bottom_limit'];
		echo "</td>\n  \t<td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info40[0]['top_limit'];
		echo "</td>\n    <td align=\"center\" bgcolor=\"#ffffff\">";
		echo $info40[0]['odd_limit'];
		echo "</td>\n\t\n\t\n\t   <td align=\"center\" bgcolor=\"#DFEFFF\" height=\"20\"></td>\n        <td align=\"center\" bgcolor=\"#ffffff\"></td>\n  \n    <td align=\"center\" bgcolor=\"#ffffff\"></td>\n    <td align=\"center\" bgcolor=\"#ffffff\"></td>\n  </tr>\n  </tbody></table></div> \n            <!-- 結束  --></td>\n            ";
}
echo "            <td background=\"../images/tab_15.gif\" width=\"8\">&nbsp;</td>\n          </tr>\n        </tbody>\n      </table></td>\n    </tr>\n    <tr>\n      <td background=\"../images/tab_19.gif\" height=\"35\"><table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\n        <tbody>\n          <tr>\n            <td height=\"35\" width=\"12\"><img src=\"../images/tab_18.gif\" height=\"35\" width=\"12\"></td>\n            <td valig";
echo "n=\"top\"><table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" height=\"30\" width=\"100%\">\n              <tbody>\n                <tr>\n                  <td align=\"center\">&nbsp;</td>\n                </tr>\n              </tbody>\n            </table></td>\n            <td width=\"16\"><img src=\"../images/tab_20.gif\" height=\"35\" width=\"16\"></td>\n          </tr>\n        </tbody>\n      </table></td>\n    </tr>\n  </tbody>\n</table>  ";
echo "\n</body></html>";
?>
