<?php
include_once( "../../../global.php" );
$db = new rate( $mydbhost, $mydbuser, $mydbpw, $mydbname, ALL_PS, $mydbcharset );
echo "<html oncontextmenu=\"return false\" xmlns=\"http://www.w3.org/1999/xhtml\">\n<head>\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=gbk\">\n";
echo "<s";
echo "tyle type=\"text/css\">\n<!--\nbody {\n\tmargin-left: 0px;\n\tmargin-top: 0px;\n\tmargin-right: 0px;\n\tmargin-bottom: 0px;\n}\n-->\n</style>\n";
echo "<s";
echo "cript>\nif(self == top) {location = '/';} \nif(window.location.host!=top.location.host){top.location=window.location;}</script>\n</head>\n\n<body oncontextmenu=\"return false\" onselect=\"document.selection.empty()\" oncopy=\"document.selection.empty()\" onmouseover=\"self.status='歡迎光臨';return true\">\n";
echo "<s";
echo "tyle type=\"text/css\">\n<!--\nbody {\n\tmargin-left: 0px;\n\tmargin-top: 0px;\n\tmargin-right: 0px;\n\tmargin-bottom: 0px;\n}\n.input1 {\tdisplay:inline-block;BACKGROUND-COLOR: #ffffff; BORDER-BOTTOM: #A7BCCB 1px solid; BORDER-LEFT: #A7BCCB 1px solid; BORDER-RIGHT: #A7BCCB 1px solid; BORDER-TOP: #A7BCCB 1px solid; FONT-FAMILY: \"Verdana\", \"Arial\", \"Helvetica\", \"sans-serif\"; FONT-SIZE: 12px;text-align:left;font-we";
echo "ight: bold;color: #990000;line-height: 15px;width: 45px;\n}\n-->\n</style>\n<link href=\"../../images/Index.css\" rel=\"stylesheet\" type=\"text/css\">\n";
echo "<s";
echo "tyle type=\"text/css\">\n<!--\na {\n\tfont-size: 14px;\n}\na:link {\n\ttext-decoration: none;\n\t\n}\na:visited {\n\ttext-decoration: none;\n\t\n}\na:hover {\n\ttext-decoration: underline;\n\t\n}\na:active {\n\ttext-decoration: none;\n}\n\n\n-->\n</style>\n";
echo "<s";
echo "cript language=\"JavaScript\">\nfunction quick5(id){\n\nfor (i=1;i<=15;i++){\ndocument.getElementById(\"date\"+i).bgColor='';\n}\n\nvar cc=document.getElementById(\"date\"+id); \ncc.bgColor='#FFFF6F';\n\n}\n</script>\n<div id=\"Menu\">\n  <table class=\"Ball_List Tab\" align=\"center\" bgcolor=\"ffffff\" border=\"0\" bordercolor=\"f1f1f1\" cellpadding=\"1\" cellspacing=\"1\" width=\"75\">\n    <tbody>\n      <tr class=\"td_caption_1\">\n       ";
echo " <td bordercolor=\"cccccc\" bgcolor=\"#DFEFFF\" nowrap=\"NOWRAP\"><div class=\"F_bold\" align=\"center\"> 默認賠率 </div></td>\n      </tr>\n      <tr onMouseOver=\"this.style.backgroundColor='#FFFFA2'\" onMouseOut=\"this.style.backgroundColor='ffffff'\" bgcolor=\"#FFFFFF\">\n        <td bordercolor=\"cccccc\" id=\"date1\" align=\"left\" bgcolor=\"FFFF6F\" height=\"25\" width=\"60\"><a href=\"#\" onClick=\"javascript:parent.b_blm.location";
echo ".href='m_tm.php';quick5(1);\">☉特码</a></td>\n      </tr>\n      <tr onMouseOver=\"this.style.backgroundColor='#FFFFA2'\" onMouseOut=\"this.style.backgroundColor='ffffff'\" bgcolor=\"#FFFFFF\">\n        <td bordercolor=\"cccccc\" id=\"date2\" align=\"left\" height=\"25\" width=\"60\"><a href=\"#\" onClick=\"javascript:parent.b_blm.location.href='m_tm.php?o=30';quick5(2);\">☉正码</a></td>\n      </tr>\n      <tr onMouseOver=\"this.s";
echo "tyle.backgroundColor='#FFFFA2'\" onMouseOut=\"this.style.backgroundColor='ffffff'\" bgcolor=\"#FFFFFF\">\n        <td bordercolor=\"cccccc\" id=\"date3\" align=\"left\" height=\"25\" width=\"60\"><a href=\"#\" onClick=\"javascript:parent.b_blm.location.href='m_tm.php?o=18';quick5(3);\">☉正1特</a></td>\n      </tr>\n      <tr onMouseOver=\"this.style.backgroundColor='#FFFFA2'\" onMouseOut=\"this.style.backgroundColor='ffffff'\" ";
echo "bgcolor=\"#FFFFFF\">\n        <td bordercolor=\"cccccc\" id=\"date4\" align=\"left\" height=\"25\" width=\"60\"><a href=\"#\" onClick=\"javascript:parent.b_blm.location.href='m_tm.php?o=20';quick5(4);\">☉正2特</a></td>\n      </tr>\n      <tr onMouseOver=\"this.style.backgroundColor='#FFFFA2'\" onMouseOut=\"this.style.backgroundColor='ffffff'\" bgcolor=\"#FFFFFF\">\n        <td bordercolor=\"cccccc\" id=\"date5\" align=\"left\" height";
echo "=\"25\" width=\"60\"><a href=\"#\" onClick=\"javascript:parent.b_blm.location.href='m_tm.php?o=22';quick5(5);\">☉正3特</a></td>\n      </tr>\n      <tr onMouseOver=\"this.style.backgroundColor='#FFFFA2'\" onMouseOut=\"this.style.backgroundColor='ffffff'\" bgcolor=\"#FFFFFF\">\n        <td bordercolor=\"cccccc\" id=\"date6\" align=\"left\" height=\"25\" width=\"60\"><a href=\"#\" onClick=\"javascript:parent.b_blm.location.href='m_tm.";
echo "php?o=24';quick5(6);\">☉正4特</a></td>\n      </tr>\n      <tr onMouseOver=\"this.style.backgroundColor='#FFFFA2'\" onMouseOut=\"this.style.backgroundColor='ffffff'\" bgcolor=\"#FFFFFF\">\n        <td bordercolor=\"cccccc\" id=\"date7\" align=\"left\" height=\"25\" width=\"60\"><a href=\"#\" onClick=\"javascript:parent.b_blm.location.href='m_tm.php?o=26';quick5(7);\">☉正5特</a></td>\n      </tr>\n      <tr onMouseOver=\"this.style.";
echo "backgroundColor='#FFFFA2'\" onMouseOut=\"this.style.backgroundColor='ffffff'\" bgcolor=\"#FFFFFF\">\n        <td bordercolor=\"cccccc\" id=\"date8\" align=\"left\" height=\"25\" width=\"60\"><a href=\"#\" onClick=\"javascript:parent.b_blm.location.href='m_tm.php?o=28';quick5(8);\">☉正6特</a></td>\n      </tr>\n      <tr onMouseOver=\"this.style.backgroundColor='#FFFFA2'\" onMouseOut=\"this.style.backgroundColor='ffffff'\" bgcol";
echo "or=\"#FFFFFF\">\n        <td bordercolor=\"cccccc\" id=\"date9\" align=\"left\" height=\"25\" width=\"60\"><a href=\"#\" onClick=\"javascript:parent.b_blm.location.href='m_lm.php';quick5(9);\">☉连码</a></td>\n      </tr>\n      <tr onMouseOver=\"this.style.backgroundColor='#FFFFA2'\" onMouseOut=\"this.style.backgroundColor='ffffff'\" bgcolor=\"#FFFFFF\">\n        <td bordercolor=\"cccccc\" id=\"date10\" align=\"left\" height=\"25\" widt";
echo "h=\"60\"><a href=\"#\" onClick=\"javascript:parent.b_blm.location.href='m_bz.php';quick5(10);\">☉不中</a></td>\n      </tr>\n      <tr onMouseOver=\"this.style.backgroundColor='#FFFFA2'\" onMouseOut=\"this.style.backgroundColor='ffffff'\" bgcolor=\"#FFFFFF\">\n        <td colspan=\"2\" bordercolor=\"cccccc\" id=\"date11\" align=\"left\" height=\"25\" nowrap=\"nowrap\"><a href=\"#\" onClick=\"javascript:parent.b_blm.location.href='m_";
echo "dqws.php';quick5(11);\">☉多肖尾数</a></td>\n      </tr>\n      <tr onMouseOver=\"this.style.backgroundColor='#FFFFA2'\" onMouseOut=\"this.style.backgroundColor='ffffff'\" bgcolor=\"#FFFFFF\">\n        <td bordercolor=\"cccccc\" id=\"date12\" align=\"left\" height=\"25\" width=\"60\"><a href=\"#\" onClick=\"javascript:parent.b_blm.location.href='m_wsl.php';quick5(12);\">☉尾数连</a></td>\n      </tr>\n      <tr onMouseOver=\"this.sty";
echo "le.backgroundColor='#FFFFA2'\" onMouseOut=\"this.style.backgroundColor='ffffff'\" bgcolor=\"#FFFFFF\">\n        <td bordercolor=\"cccccc\" id=\"date13\" align=\"left\" height=\"25\" width=\"60\"><a href=\"#\" onClick=\"javascript:parent.b_blm.location.href='m_sql.php';quick5(13);\">☉生肖连</a></td>\n      </tr>\n      <tr onMouseOver=\"this.style.backgroundColor='#FFFFA2'\" onMouseOut=\"this.style.backgroundColor='ffffff'\" bgc";
echo "olor=\"#FFFFFF\">\n        <td bordercolor=\"cccccc\" id=\"date14\" align=\"left\" height=\"25\" width=\"60\"><a href=\"#\" onClick=\"javascript:parent.b_blm.location.href='m_gg.php';quick5(14);\">☉过关</a></td>\n      </tr>\n      <tr onMouseOver=\"this.style.backgroundColor='#FFFFA2'\" onMouseOut=\"this.style.backgroundColor='ffffff'\" bgcolor=\"#FFFFFF\">\n        <td bordercolor=\"cccccc\" id=\"date15\" align=\"left\" height=\"25\" ";
echo "width=\"60\"><a href=\"#\" onClick=\"javascript:parent.b_blm.location.href='m_bb.php';quick5(15);\">☉半波</a></td>\n      </tr>\n    </tbody>\n  </table>\n</div>\n</body>\n</html>";
?>
